name: build
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build_and_test:
    name: menge_vendor
    uses: open-rmf/rmf_ci_templates/.github/workflows/reusable_build.yaml@main
    with:
      # NOTE: Avoid adding comments in the package lines, this can break some of the called scripts in github actions
      packages: |
            menge_vendor